app:
  port: 8080
  env: development

database:
  host: localhost
  user: test
  password: test
  dbname: postgres
  port: 5432
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""

jwt:
  secret: winkedin
